name: CI
on:
  push:
  pull_request:
jobs:
  build-test-212:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.11"
      - name: Coursier cache
        uses: coursier/cache-action@v5
      - name: Build and test
        run: |
          sbt ++2.12.12 clean scalafmtCheckAll test zio-k8s-crd/scripted

          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt

  build-test-213:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.11"
      - name: Coursier cache
        uses: coursier/cache-action@v5
      - name: Build and test
        run: |
          sbt ++2.13.4 clean scalafmtCheckAll zio-k8s-client/test zio-k8s-operator/test examples/compile docs/mdoc

          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt

  build-test-3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.11"
      - name: Coursier cache
        uses: coursier/cache-action@v5
      - name: Build and test
        run: |
          sbt ++3.0.0 clean zio-k8s-client/test zio-k8s-operator/test leader-example/compile logs-example/compile

          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt